[phases.setup]
nixPkgs = ['nodejs_20', 'npm-10_x']

[phases.install]
cmds = ['npm ci']

[phases.build]
cmds = ['cd backend && npm install && npx prisma generate && npm run build']

[start]
cmd = 'cd backend && npm run start:prod'