[phases.setup]
nixPkgs = ['nodejs_20']

[phases.install]
cmds = ['npm install --legacy-peer-deps', 'cd backend && npm install --legacy-peer-deps']

[phases.build]
cmds = ['cd backend && npx prisma generate && npm run build']

[start]
cmd = 'cd backend && npm run start:prod'